### ISSUE TITLE
WindowLeaked exception on rotate screen

### ISSUE THREAD

**Issue by freakdudette** [stfalcon-studio/StfalconImageViewer#12]
**Describe the bug**
A WindowLeaked exception is thrown when rotating the screen. The AlertDialog within ImageViewerDialog is not disposed.

**To Reproduce**
1. Open the ImageViewerDialog for a set of images
2. Rotate the device
4. See error:

E/WindowManager: android.view.WindowLeaked: 
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:329)
        at com.stfalcon.imageviewer.viewer.dialog.ImageViewerDialog.show(ImageViewerDialog.kt:57)
        at com.stfalcon.imageviewer.StfalconImageViewer.show(StfalconImageViewer.java:63)
        at com.stfalcon.imageviewer.StfalconImageViewer$Builder.show(StfalconImageViewer.java:316)
        at com.stfalcon.imageviewer.StfalconImageViewer$Builder.show(StfalconImageViewer.java:305)

**Expected behavior**
The exception should not be thrown and the ImageViewer objects should be cleared/dismissed when onPause is called for the starting activity

A dismiss function in ImageViewerDialog should include the dismisal of the AlertDialog object

**Comment by troy379** [comment]
Hey @freakdudette 
Sorry for such a long delay.
Please, update your library version to `0.1.1` and add [these lines as I did in the sample project](https://github.com/stfalcon-studio/StfalconImageViewer/blob/7742196eddcbabe408d73fec2917417d6d2bdbb3/sample/src/main/java/com/stfalcon/sample/features/demo/rotation/RotationDemoActivity.kt#L34-L37).
KR

**Comment by freakdudette** [comment]
@troy379 Thank you! ☺️

**Comment by L4grange** [comment]
@troy379 I'm facing the same issue and I'm trying to use the library version `0.1.1` but Android Studio is giving me the following error:

`ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.stfalcon:stfalcon-imageviewer:0.1.1.`
