### ISSUE TITLE
swipeDismissHandler has not been initialized

### ISSUE THREAD

**Issue by matthewkrueger** [stfalcon-studio/StfalconImageViewer#29]
**Describe the bug**
Great library! I'm just here to report a crash that's been popping up more and more on crashlytics in my production app that's coming from this library.

**To Reproduce**
I'm not sure how to reproduce, but I suspect it's a bug how the swipe dismiss handler is being initialized. Most recent crash was on a Galaxy J7 Crown running Android 9. I've seen a similar crash with "lateinit property transitionImageAnimator has not been initialized
       at com.stfalcon.imageviewer.viewer.view.ImageViewerView.dispatchTouchEvent(ImageViewerView.kt:155)" and can file a separate bug if needed.

`Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property swipeDismissHandler has not been initialized
       at com.stfalcon.imageviewer.viewer.view.ImageViewerView.close$imageviewer_release(ImageViewerView.kt:205)
       at com.stfalcon.imageviewer.viewer.dialog.ImageViewerDialog.onDialogKeyEvent(ImageViewerDialog.kt:83)
       at com.stfalcon.imageviewer.viewer.dialog.ImageViewerDialog.access$onDialogKeyEvent(ImageViewerDialog.kt:27)
       at com.stfalcon.imageviewer.viewer.dialog.ImageViewerDialog$1.onKey(ImageViewerDialog.kt:47)
       at android.app.Dialog.dispatchKeyEvent(Dialog.java:965)
       at androidx.appcompat.app.AppCompatDialog.superDispatchKeyEvent(AppCompatDialog.java:201)
       at androidx.appcompat.app.AppCompatDialog$1.superDispatchKeyEvent(AppCompatDialog.java:48)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
       at androidx.appcompat.app.AppCompatDialog.dispatchKeyEvent(AppCompatDialog.java:207)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:586)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6119)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5974)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5605)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5662)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5605)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5662)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5605)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5662)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8504)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8424)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8377)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8619)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:181)
       at android.app.ActivityThread.main(ActivityThread.java:7156)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

**Expected behavior**
Don't crash

**Comment by troy379** [comment]
Hey @matthewkrueger !
Which version of the library do you use?

**Comment by matthewkrueger** [comment]
Ah crap - looks like I'm on 0.1.0, but you released 1.0.0. I'll update and see if that stops it - thanks!

**Comment by KhinThiriSoe** [comment]
it also happens on 1.0.0.

**Comment by matir91** [comment]
Hi @troy379 , this issue shouldn't be closed, it's happening in the latest version, can you reopen it, please?
