### ISSUE TITLE
crash by lateinit property

### ISSUE THREAD

**Issue by iielse** [stfalcon-studio/StfalconImageViewer#7]

**Comment by iielse** [comment]
![image](https://user-images.githubusercontent.com/7521943/51231129-606fa480-199d-11e9-9e78-0ce45134736b.png)


`private lateinit var swipeDismissHandler: SwipeToDismissHandler`
`private lateinit var transitionImageAnimator: TransitionImageAnimator`

**Comment by string-areeb** [comment]
Any updates in this fix?

**Comment by DrPechkin** [comment]
@troy379, can you accept PR? please

**Comment by paulsUsername** [comment]
I am seeing this crash as well:

Stack trace:

kotlin.UninitializedPropertyAccessException: lateinit property transitionImageAnimator has not been initialized
	at com.stfalcon.imageviewer.viewer.view.ImageViewerView.dispatchTouchEvent(ImageViewerView.kt:155)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:806)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
	at android.view.View.dispatchPointerEvent(View.java:10243)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6247)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6221)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6182)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6350)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by paulsUsername** [comment]
Any sorted of a button/swipe bash at all and its crashing for me. Relatively easy to replicate.

**Comment by string-areeb** [comment]
The project is abandoned. You can use this - https://jitpack.io/#string-areeb/StfalconImageViewer/lateinit-check-SNAPSHOT

https://github.com/string-areeb/StfalconImageViewer/tree/lateinit-check

**Comment by troy379** [comment]
Hey everyone
Sorry, I haven't had a chance to work on the project. Thanks to @string-areeb for the fix, it's merged and will be applied in the `0.1.1` version. Cheers!
